// ERP Playwright Recorder — fullview.js

const TYPE_META = {
  select:        { label: 'SELECT',   color: '#7ee787' },
  input:         { label: 'INPUT',    color: '#79c0ff' },
  button:        { label: 'BUTTON',   color: '#ffa657' },
  'dialog-open': { label: 'DIALOG ▼', color: '#d2a8ff' },
  'dialog-close':{ label: 'DIALOG ▲', color: '#6e7681' },
  swal2:         { label: 'SWAL2',    color: '#f8e3a1' },
  navigate:      { label: 'NAV',      color: '#56d364' },
  row:           { label: 'ROW',      color: '#79c0ff' },
  tracking:      { label: 'TRACK',    color: '#ffa657' },
  readonly:      { label: 'READ',     color: '#a5b4fc' },
  start:         { label: 'START',    color: '#56d364' },
  search:        { label: 'SEARCH',   color: '#79c0ff' },
};

function generateCode(steps) {
  if (!steps.length) return '# No steps recorded yet.';
  const lines = ['# Generated by ERP Playwright Recorder', ''];
  for (let i = 0; i < steps.length; i++) {
    const s = steps[i];
    const prev = steps[i - 1];
    if (prev && needsBlankLine(prev.type, s.type)) lines.push('');
    if (s.type === 'navigate')       lines.push(`# ── Navigate: ${s.label} ──`);
    else if (s.type === 'dialog-open')   lines.push(`# ── Dialog opened: "${s.label}" ──`);
    else if (s.type === 'dialog-close')  lines.push(`# ── Dialog closed ──`);
    else if (s.type === 'tracking')  lines.push(`# ── PB tracking card ──`);
    lines.push(s.code);
    if (s.patched && s.patched.length) {
      const ctx = s.type === 'start'    ? 'page loaded, fields matching initial state'
                : s.type === 'navigate' ? 'auto-patched after navigation'
                : `auto-patched after "${s.label}"`;
      lines.push(`#  ${ctx}:`);
      for (const p of s.patched) {
        const lp = p.label.replace(/'/g, "\\'");
        const vq = p.value.replace(/"/g, '\\"');
        lines.push(`#    ${p.label} = "${p.value}"`);
        lines.push(p.isSelect
          ? `assert page.locator("xpath=//mat-label[contains(.,'${lp}')]/ancestor::mat-form-field//mat-select").text_content().strip() == "${vq}"`
          : `assert page.locator("xpath=//mat-label[contains(.,'${lp}')]/ancestor::mat-form-field//input").input_value() == "${vq}"`);
      }
    }
  }
  return lines.join('\n');
}

function needsBlankLine(a, b) {
  const g = {
    navigate: 0,
    'dialog-open': 1, 'dialog-close': 1,
    select: 2, input: 2,
    button: 3,
    swal2: 4, tracking: 4,
    row: 5,
    readonly: 6,
  };
  return (g[a] ?? 9) !== (g[b] ?? 9);
}

function esc(s) {
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}

let currentSteps = [];
let isRecording  = false;

function render(steps, recording) {
  currentSteps = steps || [];
  isRecording  = !!recording;

  const dot = document.getElementById('dot');
  const lbl = document.getElementById('rec-lbl');
  const btn = document.getElementById('btn-toggle');
  const cnt = document.getElementById('step-count');
  cnt.textContent = currentSteps.length + (currentSteps.length === 1 ? ' step' : ' steps');

  if (recording) {
    dot.classList.add('on'); lbl.classList.add('on');
    lbl.textContent = 'RECORDING'; btn.textContent = 'Stop'; btn.classList.add('stop');
  } else {
    dot.classList.remove('on'); lbl.classList.remove('on');
    lbl.textContent = currentSteps.length ? 'PAUSED' : 'IDLE';
    btn.textContent = 'Start'; btn.classList.remove('stop');
  }

  const list = document.getElementById('step-list');
  if (!currentSteps.length) {
    list.innerHTML = `<div class="empty"><span class="empty-dot">⏺</span><span>No steps yet.<br>Start recording and interact with the ERP.</span></div>`;
  } else {
    list.innerHTML = currentSteps.map((s, i) => {
      const m = TYPE_META[s.type] || { label: s.type.toUpperCase(), color: '#484f58' };
      return `
        <div class="step-row">
          <span class="step-num">${i + 1}</span>
          <span class="step-badge" style="color:${m.color};border-color:${m.color}22;background:${m.color}11">${m.label}</span>
          <div class="step-body">
            <div class="step-label">${esc(s.label || '')}</div>
            ${s.value ? `<div class="step-val">${esc(String(s.value).slice(0, 60))}</div>` : ''}
            <div class="step-code">${esc((s.code || '').split('\n')[0].slice(0, 70))}</div>
          </div>
        </div>`;
    }).join('');
    list.scrollTop = list.scrollHeight;
  }

  document.getElementById('code-out').value = generateCode(currentSteps);
}

// ── Communicate with the recording tab ───────────────────────────────────
// fullview is its own tab; we query ALL tabs but stop after the first response.

function sendToRecordingTab(msg, cb) {
  chrome.tabs.query({}, tabs => {
    if (chrome.runtime.lastError) return;
    let responded = false;
    for (const tab of tabs) {
      if (tab.id === chrome.tabs.TAB_ID_NONE) continue;
      if (responded) break;
      chrome.tabs.sendMessage(tab.id, msg, res => {
        if (chrome.runtime.lastError) return;
        if (res && !responded) { responded = true; if (cb) cb(res); }
      });
    }
  });
}

// ── Buttons ───────────────────────────────────────────────────────────────

document.getElementById('btn-toggle').addEventListener('click', () => {
  sendToRecordingTab({ type: 'TOGGLE_REC' }, res => render(res.steps, res.recording));
});

document.getElementById('btn-clear').addEventListener('click', () => {
  chrome.storage.local.set({ erp_steps: [], erp_recording: false });
  sendToRecordingTab({ type: 'CLEAR' }, () => {});
  render([], false);
});

document.getElementById('btn-restart').addEventListener('click', () => {
  chrome.storage.local.set({ erp_steps: [], erp_recording: true });
  sendToRecordingTab({ type: 'RESTART' }, () => {});
  render([], true);
});

document.getElementById('btn-copy').addEventListener('click', () => {
  navigator.clipboard.writeText(generateCode(currentSteps)).then(() => {
    const btn = document.getElementById('btn-copy');
    const orig = btn.textContent;
    btn.textContent = 'Copied!'; btn.classList.add('copied');
    setTimeout(() => { btn.textContent = orig; btn.classList.remove('copied'); }, 1500);
  });
});

// ── Live updates via storage polling ─────────────────────────────────────

function poll() {
  chrome.storage.local.get(['erp_steps', 'erp_recording'], data => {
    if (chrome.runtime.lastError) return;
    render(data.erp_steps || [], !!data.erp_recording);
  });
}

chrome.runtime.onMessage.addListener(msg => {
  if (msg.type === 'STATE') render(msg.steps, msg.recording);
});

poll();
setInterval(poll, 600);
