// ERP Playwright Recorder — popup script

const TYPE_META = {
  select:        { label: 'SELECT',   color: '#7ee787' },
  input:         { label: 'INPUT',    color: '#79c0ff' },
  button:        { label: 'BUTTON',   color: '#ffa657' },
  'dialog-open': { label: 'DIALOG ▼', color: '#d2a8ff' },
  'dialog-close':{ label: 'DIALOG ▲', color: '#6e7681' },
  swal2:         { label: 'SWAL2',    color: '#f8e3a1' },
  navigate:      { label: 'NAV',      color: '#56d364' },
  row:           { label: 'ROW',      color: '#79c0ff' },
  tracking:      { label: 'TRACK',    color: '#ffa657' },
  readonly:      { label: 'READ',     color: '#a5b4fc' },
  start:         { label: 'START',    color: '#56d364' },
  search:        { label: 'SEARCH',   color: '#79c0ff' },
};

let currentSteps = [];
let isRecording = false;

// ── Code generator ────────────────────────────────────────────────────────

function generateCode(steps) {
  if (!steps.length) return '# No steps recorded yet.';
  const lines = ['# Generated by ERP Playwright Recorder', ''];

  for (let i = 0; i < steps.length; i++) {
    const s = steps[i];
    const prev = steps[i - 1];
    if (prev && needsBlankLine(prev.type, s.type)) lines.push('');

    if (s.type === 'navigate')       lines.push(`# ── Navigate: ${s.label} ──`);
    else if (s.type === 'dialog-open')   lines.push(`# ── Dialog opened: "${s.label}" ──`);
    else if (s.type === 'dialog-close')  lines.push(`# ── Dialog closed ──`);
    else if (s.type === 'tracking')  lines.push(`# ── PB tracking card ──`);

    lines.push(s.code);
    if (s.patched && s.patched.length) {
      const ctx = s.type === 'start'    ? 'page loaded, fields matching initial state'
                : s.type === 'navigate' ? 'auto-patched after navigation'
                : `auto-patched after "${s.label}"`;
      lines.push(`#  ${ctx}:`);
      if (s.type === 'select') {
        // selection fired an async autofill — wait on the first patched field
        const p0 = s.patched[0];
        const nth = p0.rowIndex != null ? `.nth(${p0.rowIndex})` : '';
        const tgt = p0.isSelect ? 'mat-select' : 'input';
        const lp0 = p0.label.replace(/'/g, "\\'");
        lines.push(`page.locator("xpath=//mat-label[contains(.,'${lp0}')]/ancestor::mat-form-field//${tgt}")${nth}.wait_for(state="visible", timeout=10000)`);
      }
      for (const p of s.patched) {
        const lp = p.label.replace(/'/g, "\\'");
        const vq = p.value.replace(/"/g, '\\"');
        const nth = p.rowIndex != null ? `.nth(${p.rowIndex})` : '';
        lines.push(`#    ${p.label} = "${p.value}"`);
        lines.push(p.isSelect
          ? `assert page.locator("xpath=//mat-label[contains(.,'${lp}')]/ancestor::mat-form-field//mat-select")${nth}.text_content().strip() == "${vq}"`
          : `assert page.locator("xpath=//mat-label[contains(.,'${lp}')]/ancestor::mat-form-field//input")${nth}.input_value() == "${vq}"`);
      }
    }
  }

  return lines.join('\n');
}

function needsBlankLine(a, b) {
  const g = {
    navigate: 0,
    'dialog-open': 1, 'dialog-close': 1,
    select: 2, input: 2,
    button: 3,
    swal2: 4, tracking: 4,
    row: 5,
    readonly: 6,
  };
  return (g[a] ?? 9) !== (g[b] ?? 9);
}

// ── Render ────────────────────────────────────────────────────────────────

function esc(str) {
  return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}

function renderSteps(steps) {
  const list = document.getElementById('step-list');
  list.innerHTML = '';
  if (!steps.length) {
    list.innerHTML = '<div class="empty">No steps yet. Start recording and interact with the ERP.</div>';
    return;
  }
  [...steps].reverse().forEach(s => {
    const meta = TYPE_META[s.type] || { label: s.type.toUpperCase(), color: '#484f58' };
    const row = document.createElement('div');
    row.className = 'step-row';
    row.innerHTML = `
      <span class="step-badge" style="color:${meta.color};border-color:${meta.color}22;background:${meta.color}11">${meta.label}</span>
      <span class="step-label">${esc(s.label || '')}</span>
      ${s.value ? `<span class="step-val">${esc(String(s.value).slice(0, 40))}</span>` : ''}
    `;
    list.appendChild(row);
  });
}

function renderCode(steps) {
  document.getElementById('code-out').textContent = generateCode(steps);
}

function renderCount(steps, recording) {
  document.getElementById('step-count').textContent =
    steps.length + (steps.length === 1 ? ' step' : ' steps');
  const dot    = document.getElementById('rec-dot');
  const recLbl = document.getElementById('rec-label');
  const btn    = document.getElementById('btn-toggle');
  if (recording) {
    dot.classList.add('on'); recLbl.classList.add('on');
    recLbl.textContent = 'RECORDING';
    btn.textContent = 'Stop'; btn.classList.add('stop');
  } else {
    dot.classList.remove('on'); recLbl.classList.remove('on');
    recLbl.textContent = steps.length ? 'PAUSED' : 'IDLE';
    btn.textContent = 'Start'; btn.classList.remove('stop');
  }
}

function refresh(steps, recording) {
  currentSteps = steps || [];
  isRecording  = !!recording;
  renderSteps(currentSteps);
  renderCode(currentSteps);
  renderCount(currentSteps, isRecording);
}

// ── Query active tab ──────────────────────────────────────────────────────

function queryTab() {
  chrome.tabs.query({ active: true, currentWindow: true }, tabs => {
    if (!tabs[0]) return;
    chrome.tabs.sendMessage(tabs[0].id, { type: 'GET_STATE' }, res => {
      if (chrome.runtime.lastError) return;
      if (res) refresh(res.steps, res.recording);
    });
  });
}

// ── Button handlers ───────────────────────────────────────────────────────

document.getElementById('btn-toggle').addEventListener('click', () => {
  chrome.tabs.query({ active: true, currentWindow: true }, tabs => {
    if (!tabs[0]) return;
    chrome.tabs.sendMessage(tabs[0].id, { type: 'TOGGLE_REC' }, res => {
      if (chrome.runtime.lastError) return;
      if (res) refresh(res.steps, res.recording);
    });
  });
});

document.getElementById('btn-clear').addEventListener('click', () => {
  chrome.tabs.query({ active: true, currentWindow: true }, tabs => {
    if (!tabs[0]) return;
    chrome.tabs.sendMessage(tabs[0].id, { type: 'CLEAR' }, () => {
      if (chrome.runtime.lastError) return;
      refresh([], false);
    });
  });
});

document.getElementById('btn-restart').addEventListener('click', () => {
  chrome.tabs.query({ active: true, currentWindow: true }, tabs => {
    if (!tabs[0]) return;
    chrome.tabs.sendMessage(tabs[0].id, { type: 'CLEAR' }, () => {
      if (chrome.runtime.lastError) return;
      chrome.tabs.sendMessage(tabs[0].id, { type: 'RESTART' }, res => {
        if (chrome.runtime.lastError) return;
        if (res) refresh(res.steps, res.recording);
      });
    });
  });
});

document.getElementById('btn-copy').addEventListener('click', () => {
  navigator.clipboard.writeText(generateCode(currentSteps)).then(() => {
    const btn = document.getElementById('btn-copy');
    btn.textContent = 'Copied!'; btn.classList.add('copied');
    setTimeout(() => { btn.textContent = 'Copy'; btn.classList.remove('copied'); }, 1500);
  });
});

// ── Init ──────────────────────────────────────────────────────────────────

chrome.runtime.onMessage.addListener(msg => {
  if (msg.type === 'STATE') refresh(msg.steps, msg.recording);
});

queryTab();

setInterval(() => {
  chrome.storage.local.get(['erp_steps', 'erp_recording'], data => {
    if (chrome.runtime.lastError) return;
    if (data.erp_steps !== undefined) refresh(data.erp_steps, data.erp_recording);
  });
}, 600);
