# supplier_mkdir.ps1
# PowerShell script to create the Supplier Screen automation folder structure
# Run from the project root directory

$base = "pages\dynamic_screens\modules\supplier"

# Create directories
$dirs = @(
    "$base",
    "$base\data",
    "$base\test",
    "$base\reports"
)

foreach ($dir in $dirs) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        Write-Host "Created: $dir" -ForegroundColor Green
    } else {
        Write-Host "Exists:  $dir" -ForegroundColor Yellow
    }
}

# Create __init__.py files
$initFiles = @(
    "$base\__init__.py",
    "$base\data\__init__.py",
    "$base\test\__init__.py"
)

foreach ($initFile in $initFiles) {
    if (-not (Test-Path $initFile)) {
        Set-Content -Path $initFile -Value "" -NoNewline
        Write-Host "Created: $initFile" -ForegroundColor Cyan
    } else {
        Write-Host "Exists:  $initFile" -ForegroundColor Yellow
    }
}

# Copy files from download to project structure
$downloadDir = "C:\Users\$env:USERNAME\Downloads"
$sourceDir = Split-Path -Parent $MyInvocation.MyCommand.Path

Write-Host ""
Write-Host "Folder structure:" -ForegroundColor White
Write-Host ""
Write-Host "  pages/" -ForegroundColor White
Write-Host "    dynamic_screens/" -ForegroundColor White
Write-Host "      modules/" -ForegroundColor White
Write-Host "        supplier/" -ForegroundColor White
Write-Host "          __init__.py" -ForegroundColor Gray
Write-Host "          supplier_page.py      <- Page Object (stepper form)" -ForegroundColor Cyan
Write-Host "          data/" -ForegroundColor White
Write-Host "            __init__.py" -ForegroundColor Gray
Write-Host "            supplier_data.py     <- Test data generators" -ForegroundColor Cyan
Write-Host "          test/" -ForegroundColor White
Write-Host "            __init__.py" -ForegroundColor Gray
Write-Host "            conftest.py          <- Fixtures (Rular@admin login)" -ForegroundColor Cyan
Write-Host "            test_supplier_validation.py  <- 42 test cases" -ForegroundColor Cyan
Write-Host "          reports/" -ForegroundColor White
Write-Host "            (auto-generated by CSReportStore)" -ForegroundColor Gray
Write-Host ""
Write-Host "Files to copy from download/:" -ForegroundColor White
Write-Host "  supplier_page.py        -> pages/dynamic_screens/modules/supplier/" -ForegroundColor Yellow
Write-Host "  supplier_data.py        -> pages/dynamic_screens/modules/supplier/data/" -ForegroundColor Yellow
Write-Host "  supplier_conftest.py    -> pages/dynamic_screens/modules/supplier/test/conftest.py" -ForegroundColor Yellow
Write-Host "  test_supplier_validation.py -> pages/dynamic_screens/modules/supplier/test/" -ForegroundColor Yellow
Write-Host ""
Write-Host "Done! Now copy the 4 Python files into the structure." -ForegroundColor Green

# Auto-copy if files are in the same directory as this script
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$filesToCopy = @{
    "$scriptDir\supplier_page.py" = "$base\supplier_page.py"
    "$scriptDir\supplier_data.py" = "$base\data\supplier_data.py"
    "$scriptDir\supplier_conftest.py" = "$base\test\conftest.py"
    "$scriptDir\test_supplier_validation.py" = "$base\test\test_supplier_validation.py"
}

$copied = 0
foreach ($src in $filesToCopy.Keys) {
    $dest = $filesToCopy[$src]
    if (Test-Path $src) {
        Copy-Item -Path $src -Destination $dest -Force
        Write-Host "Copied: $src -> $dest" -ForegroundColor Green
        $copied++
    }
}

if ($copied -gt 0) {
    Write-Host ""
    Write-Host "$copied files copied successfully!" -ForegroundColor Green
} else {
    Write-Host ""
    Write-Host "No files auto-copied (source files not found next to this script)." -ForegroundColor Yellow
    Write-Host "Please manually copy the 4 Python files into the structure." -ForegroundColor Yellow
}
